#!/bin/env bash
helpstr="FAJOIN - join the lines of each sequence in a FASTA file
Usage: fajoin FILE

Options:
 -h: Print this help message and exit

NOTE: Currently very slow; Python might work better.
"

unset file
while [ $OPTIND -le $# ]; do
    while getopts "h" opt; do
        case "$opt" in
            h)
                echo "$helpstr"
                exit
                ;;
            *)
                echo "Invalid argument:" $opt >&2
                echo "$helpstr"
                exit 1
        esac
    done
    if [[ -z "$file" ]]; then
        file=${@:$OPTIND:1}
        OPTIND=$(expr $OPTIND + 1)
    fi
done
shift $((OPTIND-1))

# Argument errors and warnings:
if [[ -z $file ]]; then
    >&2 echo "Error: Input file required."
    echo "$helpstr"
    exit 1
fi

# Script:
headchar=$(awk '/./{print;exit}' "$file" | cut -c1)
if [[ "$headchar" != ">" ]]; then
    >&2 echo "Error: input file must be in FASTA format."
    exit 1
else
    headers=$(headgrep "$file")
    nscaf=$(echo "$headers" | wc -l | cut -d" " -f1)
    for i in $(seq 1 $nscaf); do
        >&2 echo -n "$i "
        echo "$headers" | sed "${i}q;d" | cut -d':' -f2
        index -xs "$i" "$file" 1 len
    done
fi
exit
